version: '3'

services:
  traefik:
    image: djpic/traefik:latest
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/traefik.yml:/traefik.yml:ro
      - /etc/traefik/acme.json:/acme.json
      - /etc/traefik/dynamic_conf:/etc/traefik/dynamic_conf
      - /var/log/traefik:/var/log/traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
